name: Deploy Laravel & ReactJS App

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Debug environment variables (correction apportée)
      - name: Debug environment variables
        run: echo "Docker Hub Username: $DOCKER_HUB_USERNAME"
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}

      # 4. Build and push Laravel image
      - name: Build and push Laravel image
        run: |
          docker build ./dashbord_api -t ${{ secrets.DOCKER_HUB_USERNAME }}/laravel-app:${{ github.sha }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/laravel-app:${{ github.sha }}

      # 5. Build and push React image
      - name: Build and push React image
        run: |
          docker build ./frontenddashboard -t ${{ secrets.DOCKER_HUB_USERNAME }}/react-app:${{ github.sha }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/react-app:${{ github.sha }}

      # 6. Deploy to production server (facultatif, activable)
      # - name: Deploy to server
      #   if: github.ref == 'refs/heads/main'
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.PROD_SERVER_HOST }}
      #     username: ${{ secrets.PROD_SERVER_USER }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     script: |
      #       docker-compose -f docker-compose.prod.yml pull
      #       docker-compose -f docker-compose.prod.yml up -d

      # 7. Deploy to staging server (facultatif)
      # - name: Deploy to staging server
      #   if: github.ref == 'refs/heads/staging'
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.STAGING_SERVER_HOST }}
      #     username: ${{ secrets.STAGING_SERVER_USER }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     script: |
      #       docker-compose -f docker-compose.staging.yml pull
      #       docker-compose -f docker-compose.staging.yml up -d
